### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by OpusManning** [jlinkels/tclmpv#5]
Hello,
Just curious, have you considered adding video support to this?  
Steve

**Comment by jlinkels** [comment]
Hi Steve,

For 2 reasons I have decided not to, at least not in the near future.

First, for my application I only need audio. It is a player which plays 
recorded audio streams from internet radio stations with a time shift to 
compensate for time zone differences. I used to run this application 
while executing the mpv application as external program. To get the 
status I piped the mpv output to stderr and stdout back into my 
application. In the mpv documentation this use case is explicitely 
mentioned as incorrect. So that is why I completed tclmpv after finding 
the code snippet.

Secondly (and most important) while it is easy and straightforward to 
play back audio in Tcl/Tk, creating a video output is much more 
complicated. I know there are some pointers, but it does not seems 
something like a simple project.


Met vriendelijke groet

Johannes Linkels

Linxtech Logo

**Comment by OpusManning** [comment]
Got it, thanks for your reply...
I'm looking at either MPV or VLC, and there does seem to be TclTk bindings
for VLC.
I wish that I programmed in C!  I have K&R, I should probably just study it
and work at it...
Cool project you have
Steve
